title: Producto
columns:
  left:
    width: 1/2
    sections:
      picture:
        type: fields
        fields:
          picture:
            type: files
            label: Fotografia de integrante
            max: 1
            layout: cards
            size: huge
            image:
              cover: true

  right:
    width: 1/2
    sections:
      content:
        type: fields
        fields:
          price:
            type: number
            label: precio
          description:
            type: textarea
            label: Descripción
          tallas:
            type: multiselect
            label: Tallas
            options:
              - XCH
              - CH
              - M
              - G
              - XG
              - XXG